dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.120.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.120.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlphttpexporter v0.120.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.120.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sapmexporter v0.120.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter v0.120.1



processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.120.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.120.1
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.119.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.120.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.120.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/signalfxreceiver v0.120.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.121.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0

